# Generated by Django 5.2.4 on 2025-08-30 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_appointment_department_appointment_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
