# Generated by Django 5.2.4 on 2025-10-27 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=250)),
                ('doctor_post', models.CharField(max_length=250)),
                ('doctor_img', models.ImageField(blank=True, null=True, upload_to='doctors')),
            ],
        ),
    ]
